databases:
  - name: Wheels-4-Rent
    databaseName: Wheels-4-Rent
    user: Wheels-4-Rent

services:
  - type: web
    name: Wheels-4-Rent
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Wheels-4-Rent
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false