default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 7868
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wheels_4_rent_backend_development
  username: postgres
  password: 7868

test:
  <<: *default
  database: wheels_4_rent_backend_development

production:
  <<: *default
  database: wheels_4_rent_backend_production
  username: wheels_4_rent_backend
  password: <%= ENV["WHEELS_4_RENT_BACKEND_DATABASE_PASSWORD"] %>
